name: 'Random user'
email: 'random@gmail.com'
merek: 'New merek'
nomor_registrasi: '123aba'
nama_pemilik: 'Raj Ramani'
hubungan_pelapor: 'Owns the property'
nama_perusahaan: 'abc Company'
website_perusahaan: 'abc.com'
alamat_perusahaan: 'demo text'
alamat_email_pemilik_merek: 'abc@gmail.com'
no_telepon_pelapor: '+917987987987'
link_barang: 'product.co.com'
body: 'problem demo text of 20 charecters'
link_barang_banyak_path: 'C:\Users\akash\Downloads\6539f1bdd85a4d04f3ad2800.pdf'
surat_kepemilikan_merek_path: 'C:\Users\akash\Downloads\6539f1bdd85a4d04f3ad2800.pdf'
bukti_surat_kuasa_path: 'C:\Users\akash\Downloads\6539f1bdd85a4d04f3ad2800.pdf'
bukti_surat_izin_usaha_path: 'C:\Users\akash\Downloads\6539f1bdd85a4d04f3ad2800.pdf'